Titanic Dataset for beginers

In [207]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

To know the present working directory

In [208]:
pwd

'/Users/taruninarra/Documents/Data Science trainiing'

To change working directory

In [209]:
import os 
os.chdir('/Users/taruninarra/Documents/Data Science trainiing')

In [210]:
pwd


'/Users/taruninarra/Documents/Data Science trainiing'

In [211]:
df=pd.read_csv('titanic/train.csv')

In [212]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [213]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


Change Female to 1 and male to 0

In [214]:
df['Sex']=df['Sex'].map({'female':1,'male':0})

In [215]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

Fill null values of age with average of age

In [216]:
df['Age'].fillna(value=df.Age.mean(),inplace=True)

In [217]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null int64
Age            891 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(6), object(4)
memory usage: 83.7+ KB


create a column with first class passengers

In [218]:
df['FirstClass']=df['Pclass'].apply(lambda x: 1 if x == 1 else 0)

create a column with second class passengers

In [219]:
df['SecondClass']=df['Pclass'].apply(lambda x: 1 if x == 2 else 0)

create a column with third class passengers

In [220]:
df['ThirdClass']=df['Pclass'].apply(lambda x: 1 if x == 3 else 0)

In [221]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin Embarked  FirstClass  SecondClass  \
0         A/5 21171   7.2500   NaN        S           0            0   
1          PC 17599  71.2833   C85        C           1            0   
2  STON/O2. 3101282   7.9250   NaN        S           0            0   
3            113803  53.1000  C123        S           1            0   
4            373450   8.0500   NaN        S           0            0   

   ThirdClass  
0           1  
1           0  
2           1  
3           0  
4           1

In [222]:
features=df[['Sex','Age','FirstClass','SecondClass','ThirdClass']]
survival=df['Survived']


In [223]:
X_train,X_test,y_train,y_test=train_test_split(features,survival,test_size = 0.2)


Scaling Data


In [224]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

Training the model

In [225]:
model=LogisticRegression()
model.fit(X_train,y_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

We can Predict Whether Passenger Survived or not with approximately 80% certainity

In [226]:
print(model.score(X_train, y_train))
print(model.score(X_test, y_test))

0.7949438202247191
0.8156424581005587


How Significant are the values in order df[['Sex','Age','FirstClass','SecondClass','ThirdClass']]. Looks like Gender plays important role.

In [227]:
print(model.coef_)

[[ 1.21741259 -0.4609069   0.54022349  0.05902535 -0.51214937]]


Let’s use our model to make predictions on the survival of a few fateful passengers.

In [228]:
Jack = np.array([0.0,20.0,0.0,0.0,1.0])
Rose = np.array([1.0,17.0,1.0,0.0,0.0])
You = np.array([1.0,26.0,0.0,0.0,1.0])

In [229]:
sample_passengers=np.array([Jack,Rose,You])

scaling

In [230]:
sample_passengers=scaler.transform(sample_passengers)
print(sample_passengers)

[[-0.74015275 -0.72629223 -0.56221111 -0.51880845  0.90864791]
 [ 1.35107247 -0.95742136  1.77869129 -0.51880845 -1.10053629]
 [ 1.35107247 -0.26403397 -0.56221111 -0.51880845  0.90864791]]


Prediction Whether survived ==1 or not survived==0

In [231]:
print(model.predict(sample_passengers))

[0 1 1]


predict_proba predicts the prabability of [0(not surviived),1(survived)] for each sample

In [232]:
print(model.predict_proba(sample_passengers))

[[0.87560793 0.12439207]
 [0.04767288 0.95232712]
 [0.40580233 0.59419767]]


Lets know the predictive power  our data with testing dataset

In [233]:
test_data=pd.read_csv('titanic/test.csv')

In [234]:
test_data.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [235]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Name           418 non-null object
Sex            418 non-null object
Age            332 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Ticket         418 non-null object
Fare           417 non-null float64
Cabin          91 non-null object
Embarked       418 non-null object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


Change Female to 1 and male to 0

In [236]:
test_data['Sex']=test_data['Sex'].map({'female':1,'male':0})

Fill null values of age with average of age

In [237]:
test_data['Age'].fillna(value=test_data.Age.mean(),inplace=True)

create column's with first class ,second class, third class passengers.

In [238]:
test_data['FirstClass']=test_data['Pclass'].apply(lambda x: 1 if x == 1 else 0)

In [239]:
test_data['SecondClass']=test_data['Pclass'].apply(lambda x: 1 if x == 2 else 0)

In [240]:
test_data['ThirdClass']=test_data['Pclass'].apply(lambda x: 1 if x == 3 else 0)

In [241]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 14 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Name           418 non-null object
Sex            418 non-null int64
Age            418 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Ticket         418 non-null object
Fare           417 non-null float64
Cabin          91 non-null object
Embarked       418 non-null object
FirstClass     418 non-null int64
SecondClass    418 non-null int64
ThirdClass     418 non-null int64
dtypes: float64(2), int64(8), object(4)
memory usage: 45.8+ KB


In [242]:
feature=test_data[['Sex','Age','FirstClass','SecondClass','ThirdClass']]



In [243]:
feature=scaler.transform(feature)

In [245]:
predicted=model.predict(feature)

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [247]:
actual=pd.read_csv('titanic/gender_submission.csv')

In [248]:
actual.head()

PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [249]:
actual_val=actual['Survived']

In [250]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_true=actual_val, y_pred=predicted)

array([[256,  10],
       [  6, 146]])

In [254]:
from sklearn.metrics import precision_score, recall_score, f1_score

In [255]:
precision_score(y_true=actual_val, y_pred=predicted)

0.9358974358974359

In [256]:
recall_score(y_true=actual_val, y_pred=predicted)

0.9605263157894737

In [257]:
f1_score(y_true=actual_val, y_pred=predicted)

0.948051948051948